// <auto-generated />
namespace finnfox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_aspNetUser_UserLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_aspNetUser_UserLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201909041913098_add_aspNetUser_UserLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
