// <auto-generated />
namespace finnfox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodata_KolicinaNovca_i_Valuta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodata_KolicinaNovca_i_Valuta));
        
        string IMigrationMetadata.Id
        {
            get { return "201909071730456_Dodata_KolicinaNovca_i_Valuta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
