// <auto-generated />
namespace finnfox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Foreign_Key_To_IdentityUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foreign_Key_To_IdentityUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201909071157021_Foreign_Key_To_IdentityUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
